class Makanan {
  final String nama;
  final String khas;
  final String description;
  final String gambar;

  Makanan(
      {required this.nama,
      required this.khas,
      required this.description,
      required this.gambar});
}

var dataMakanan = [
  Makanan(
      nama: 'Ayam Taliwang',
      khas: 'Lombok',
      description:
          'Olahan ayam dari pulau Lombok ini berasal dari masyarakat Karang'
          ' Taliwang, Kecamatan Cakranegara, Kota Mataram NTB. Ayam kampung muda yang'
          ' diolah dengan cara sederhana. Dibakar di atas bara api dengan bumbu cabe yang pedas menggigit.'
          ' Jika ingin bosan dengan ayam bakar kecap, coba saja bikin ayam bakar Taliwang'
          ' yang pedas nendang dan bikin ketagihan. Ikuti saja petunjuk resep berikut ini.'
          '\n'
          ' \nBahan :'
          ' \n1 ekor ayam kampung muda'
          ' \n1 buah jeruk nipis, ambil airnya'
          ' \n1 sdt garam'
          ' \n4 sdm minyak sayur'
          ' \n'
          ' \nHaluskan:'
          ' \n10 buah cabe keriting'
          ' \n5 buah cabe merah kering'
          ' \n5 buah cabe rawit merah'
          ' \n2 cm kencur'
          ' \n5 butir bawang merah'
          ' \n3 siung bawang putih'
          ' \n1 buah tomat merah, potong kecil'
          ' \n1 sdt gula merah'
          ' \n1 sdt terasi goreng'
          ' 1 sdt garam'
          ' \nPelengkap:'
          ' \nJeruk limau'
          ' \n'
          ' \nCara Membuat :'
          ' \n-Belah ayam membujur di bagian dadanya lalu tekan hingga terbuka.'
          ' \nLipat sayap ayam ke arah belakang.'
          ' \n-Lumuri ayam dengan air jeruk nipis dan garam hingga rata.'
          ' \n-Bumbu: Panaskan minyak, tumis bumbu halus hingga harum dan matang.'
          ' \n-Angkat dan dinginkan.'
          ' \n-Panggang ayam di atas bara api sambil balik-baik hingga ayam kaku.'
          ' \n-Olesi Bumbu sambil balik-balik beberapa kali hingga daging ayam'
          ' \nmatang dan Bumbu meresap.'
          ' \n-Taruh ayam dalam loyang atau wadah yang sudah diolesi minyak sayur.'
          ' \n-Olesi lagi dengan sisa Bumbu dan panggang dalam oven panas selama 20 menit.'
          ' \n-Angkat, sajikan dengan kucuran air jeruk limau.'
          ' \n'
          ' \nTips:'
          ' \n• Selain ayam kampung muda, ayam Taliwang Lombok juga bisa dibuat'
          '   \nmemakai ayam jantan. Ayam bisa juga dipotong 4 bagian.'
          ' \n• Bisa juga memakai ayam negeri hanya saja daging ayam lebih'
          '   \nberminyak dan lembut.'
          ' \n• Karena ayam kampung berukuran kecil biasanya disajikan 1 ekor'
          '   \nuntuk 1 orang.'
          ' \n• Ayam Taliwang Lombok biasa disajikan dengan Pelecing Kangkung'
          '   \ndan Beberuk Terung serta nasi putih.',
      gambar: 'images/1.jpg'),
  Makanan(
      nama: 'Binte Biluhuta',
      khas: 'Gorontalo',
      description:
          'Binte biluhuta adalah salah satu makanan tradisional khas daerah'
          ' Gorontalo yang cukup populer di kalangan wisatawan. Secara harfiah,'
          ' binte berarti jagung dan biluhuta berarti disiram. Jika digabungkan,'
          ' arti keduanya jagung disiram atau milu siram menurut istilah penduduk'
          ' lokal. Milu adalah nama lain jagung bagi orang Gorontalo.'
          ' Makanan tradisional ini rasanya sangat enak dan khas yang diperoleh'
          ' dari campuran bumbu pedas, asin, sekaligus manis. Cara pembuatan binte'
          ' biluhuta ini terbilang mudah. Kalau belum berkesempatan ke sana, kita'
          ' bisa mencoba membuatnya sendiri makanan khasnya ini.'
          '\n'
          '\nBahan-bahan yang diperlukan:'
          ' \n4 buah jagung manis muda'
          ' \n1 buah kelapa parut'
          ' \nIkan tongkol'
          ' \nJeruk nipis secukupnya'
          ' \nIrisan daun bawang secukupnya'
          ' \nDaun kemangi secukupnya'
          ' \nBawang goreng secukupnya'
          ' \nPenyedap rasa'
          ' \nGaram secukupnya'
          ' \nKecap secukupnya'
          ' \n12 buah cabai rawit'
          ' \n2 siung bawang merah'
          '\n'
          '\nCara Pembuatan:'
          ' \nPipilkan 4 buah jagung muda.'
          ' \nDidihkan air secukupnya.'
          ' \nMasukkan pipilan jagung tadi ke dalam air yang mendidih.'
          ' \nTambahkan garam dan penyedap rasa sesuai selera.'
          ' \nTunggu sampai rebusan jagung manis itu matang. Kurang lebih'
          ' membutuhkan waktu selama 25 menit.'
          ' \nSambil menunggu, lanjut ke langkah berikutnya yuk!'
          '\n'
          '\n Bahan Pelengkap'
          ' \nIkan tongkol suwir'
          ' \nKelapa parut yang dikukus'
          ' \nSambal (uleg 12 cabai rawit dan dua siung bawang merah.'
          '\n'
          '\nCara menghidangkan binte biluhuta:'
          ' \nSiapkan sebuah mangkuk.'
          ' \nTaruh ikan tongkol suwir, kelapa parut kukus, irisan daun bawang,'
          ' dan daun kemangi secukupnya ke dalam mangkuk.'
          ' \nSetelah itu, tuang jagung yang sudah masak tadi bersama dengan kuahnya.'
          ' \nTerakhir, tambahkan bawang goreng, sambal, kecap, dan perasan jeruk nipis sesuai selera.'
          ' \nJika mau, kamu juga boleh menambahkan garam dan bumbu penyedap rasa hingga enak dan lezat.'
          ' \nSiap disajikan!',
      gambar: 'images/2.jpg'),
  Makanan(
      nama: 'Daging Asap',
      khas: 'NTT',
      description: 'Sei merupakan daging asap yang berasal dari Provinsi Nusa'
          ' Tenggara Timur. Kuliner satu ini belakangan sedang nge-hits dan jadi'
          ' favorit banyak orang di berbagai wilayah.'
          ' Sei sendiri berasal dari bahasa Rote yang artinya daging yang diiris'
          ' tipis memanjang. Awalnya sei menggunakan daging rusa. Namun, karena '
          ' populasi rusa semakin langka, maka sekarang yang banyak dipakai adalah'
          ' daging sapi atau daging babi.'
          ' Cara memasak sei tergolong unik. Daging biasanya akan dimasak dengan'
          ' kayu bakar yang berjarak jauh, sehingga bukan lidah api yang '
          ' mematangkan daging, melainkan asap panas.'
          '\n'
          '\nBahan utama:'
          ' \n- 250 gram daging sapi (iris tipis)'
          '\n'
          '\nBahan bumbu marinasi:'
          ' \n- 2 siung bawang putih'
          ' \n- garam secukupnya'
          ' \n- merica secukupnya'
          '\n'
          '\nCara membuat sei sapi'
          ' \n1. Pertama, cincang halus bawang putih. '
          ' \n Karena cara membuat sei sapi adalah dengan pengasapan, maka '
          ' langkah selanjutnya yang perlu kamu lakukan adalah mempersiapkan tungku api.'
          '\nMarinasi daging dengan bawang putih yang sudah dicincang, garam,'
          ' dan merica. Diamkan selama sekitar 30 menit agar meresap.'
          '\nSiapkan tungku pengasapan. Saat hendak memasukkan daging jangan'
          ' lihat dari seberapa besar apinya, tapi terlihat dari asap yang sudah'
          ' mulai banyak dan semakin panas. Pastikan daging tidak bersentuhan'
          ' langsung dengan api.'
          '\nBiarkan daging sapi di dalam tungku. Waktu yang dibutuhkan untuk'
          ' mengasapi daging bervariasi, bisa satu jam hingga sembilan jam, '
          ' tergantung ukuran potongan dan jumlah daging yang diasapi.',
      gambar: 'images/3.jpg'),
  Makanan(
      nama: 'Gudeg',
      khas: 'Yogyakarta',
      description:
          'Gudeg dapat dianggap sebagai makanan vegetarian, karena hanya terdiri'
          ' dari nangka mentah dan santan. Namun, gudeg umumnya disajikan dengan'
          ' telur atau ayam. Gudeg disajikan dengan nasi kukus putih, ayam baik '
          ' sebagai opor ayam atau ayam goreng, telur pindang, opor telur atau '
          ' telur sekadar rebus, tahu dan atau tempe, dan sambel goreng krecek sup'
          ' yang terbuat dari kulit sapi renyah.'
          '\n'
          '\nBahan :'
          '\n1 kg nangka muda'
          '\n5 butir telur ayam rebus, kupas'
          '\n2 lembar daun salam'
          '\n3 lembar daun jeruk'
          '\n3 cm lengkuas, memarkan'
          '\n120 g gula Jawa yang cokelat tua'
          '\n1.5 liter santan sedang'
          '\n500 ml santan kental'
          '\n'
          '\nBumbu:'
          '\n8 butir bawang merah'
          '\n5 siung bawang putih'
          '\n5 butir kemiri'
          '\n1 sdm ketumbar'
          '\n1 potong terasi'
          '\n1/4 sdt jintan'
          '\n2 sdt garam'
          '\n'
          '\nPelengkap:'
          '\nSambal goreng krecek'
          '\nOpor ayam'
          '\nSambal bajak'
          '\n'
          '\nCara Membuat :'
          '\n1. Potong nangka muda berbentuk dadu besar. Rebus nangka muda dalam '
          'air atau air kelapa tua secukupnya hingga lunak. Angkat dan tiriskan '
          'nangka muda.'
          '\n2. Bumbu Halus: Haluskan semua bahan bumbu dengan blender atau ulekan'
          'hingga halus benar'
          '\n3. Masukkan nangka muda dan telur ke dalam panci. Tuangi santan, '
          'masukkan bumbu halus, daun salam, daun jeruk, lengkuas dan gula merah.'
          '\n4. Masak dengan api sedang hingga bumbu meresap dan kuahnya susut.'
          '\n5. Tuangkan santan kental. Masak dengan api hingga kuah benar-benar '
          'susut. Matikan api.'
          '\n6. Sajikan gudeg dengan pelengkapnya.',
      gambar: 'images/4.jpg'),
  Makanan(
      nama: 'Gulai Belacan',
      khas: 'Riau',
      description:
          'Gulai banyak macamnya di setiap daerah di Indonesia, di antara lainnya'
          ' ada gulai ayam Padang, gulai ikan, gulai daging sapi, hingga termasuk'
          ' gulai belacan yang berasal dari Riau.'
          ' Ternyata Riau juga memiliki gulai yang tak kalah nikmatnya. Terkenal'
          ' dengan memiliki rasa manis, pedas, gurih, asam, dan kuah lezatnya yang'
          ' kental sehingga memberikan keunikan tersendiri dibanding gulai lainnya.'
          '\n'
          'Untuk ingin mencoba rasa sensasi gulai belacan khas Riau ini, boleh'
          'dicoba nih resepnya di bawah ini.'
          '\n'
          'Bahan:'
          '\n300 gram udang ukuran sedang'
          '\n350 ml santan'
          '\n1 sdm air asam jawa'
          '\n1 buah jeruk nipis'
          '\n2 lembar daun jeruk'
          '\n1 sdt merica'
          '\nGaram dan gula secukupnya'
          '\nMinyak goreng secukupnya'
          '\n'
          '\nBahan bumbu halus:'
          '\n4 siung bawang putih'
          '\n7 siung bawang merah'
          '\n3 buah kemiri'
          '\n2 sdt terasi, digoreng'
          '\n4 cabai merah besar'
          '\n4 cabai rawit merah',
      gambar: 'images/5.jpg'),
  Makanan(
      nama: 'Nasi Lawar',
      khas: 'Bali',
      description:
          'Lawar Bali merupakan salah satu makanan khas Bali yang terbuat dari'
          'campuran sayur dan daging serta diberikan bumbu untuk menambah cita'
          'rasa dari hidangan ini. Lawar biasanya disajikan ketika terdapat'
          'upacara atau hari raya keagamaan. Selain itu, lawar juga sudah biasa di'
          'konsumsi oleh warga Bali atau disajikan sebagai sesajen.'
          '\n'
          '\nBahan-bahan :'
          '\n200 gr kacang panjang, potong ukuran 1/2 cm, rebus'
          '\n100 gr kelapa parut, sangrai '
          '\n3 siung bawang putih, kupas, iris, lalu goreng '
          '\n6-8 butir bawang merah, kupas, iris, goreng '
          '\n2 buah cabai merah, buang bijinya, potong serong'
          '\n4-6 butir cabai jawa, iris '
          '\n3 sdt cabai kering giling '
          '\n2 sdm bumbu kaldu ayam'
          '\nBawang goreng secukupnya untuk hiasan'
          '\n'
          '\nBahan Isi: '
          '\n250 gr daging ayam tanpa tulang, iris kecil-kecil atau disuwir '
          '\n2 sdm bumbu kaldu ayam'
          '\n1 sdt air perasan jeruk nipis'
          '\n1 sdt garam '
          '\n1/2 sdt lada hitam, haluskan'
          '\nDaun pisang untuk membungkus'
          '\n'
          '\nLangkah-langkah'
          '\nCampurkan kacang panjang, kelapa, bawang merah, bawang putih,'
          'cabai, dan bumbu kaldu ayam di dalam mangkuk. Aduk dengan rata.'
          '\nUntuk isi, campurkan irisan atau suwiran ayam dengan 2 sdm bumbu'
          'kaldu ayam. Aduk rata hingga membentuk semacam adonan. Setelah itu,'
          'letakkan adonan memanjang di atas daun pisang dan gulung hingga padat.'
          '\nKukus gulungan selama 20 menit. Lepaskan daun pisah. Pisahkan'
          'daging ayam dengan garpu.'
          '\nCampurkan daging ayam dengan kacang panjang rebus. Tambahkan garam,'
          'merica, dan perasan jeruk nipis.'
          '\nHias dengan bawang goreng renyah. Hidangan telah siap disajikan',
      gambar: 'images/6.jpg'),
  Makanan(
      nama: 'Rujak Cingur',
      khas: 'Jawa Timur',
      description:
          'Rujak cingur berasal dari daerah  Jawa Timur, lebih tepatnya'
          'Surabaya. Di beberapa kota di dekat Surabaya, juga banyak yang'
          'menjajakan menu kuliner ini dan menjualnya dalam harga murah. Yang'
          'membuat makanan ini berbeda adalah kehadiran cingur. Cingur sendiri'
          'adalah daging lunak yang diambil dari bagian bibir sapi yang telah direbus.'
          '\n'
          'Bila sedang ngidam dan ingin memakan rujak cingur Surabaya, tak ada'
          'salahnya untuk membuat resep ini di rumah. Pastikan untuk menyiapkan'
          'segala bahannya. Mulai dari cingur, sayuran, hingga racikan bumbu ulegnya.'
          '\n'
          '\nBahan-Bahan:'
          '\n250 gr cingur sapi, rebus terlebih dahulu'
          '\n1/2 papan tempe'
          '\n2 buah tahu'
          '\n50 gr taoge'
          '\n2 ikat kangkung'
          '\n1 buah mentimun'
          '\n1 buah bengkuang'
          '\n2 buah pisang klutuk atau pisang batu, parut kasar'
          '\n'
          '\nBahan Bumbu:'
          '\n8 buah cabai rawit, jumlah sesuai selera'
          '\n3 sdm kacang tanah goreng'
          '\n2 sdm gula merah, iris tipis'
          '\n¼ sdt garam secukupnya'
          '\n2 sdm petis udang'
          '\n2 siung bawang putih goreng'
          '\n4 sdm air asam jawa'
          '\nair secukupnya'
          '\n'
          '\nCara Membuat'
          '\nSebagai ciri khas rujak cingur, masak cingur terlebih dahulu dengan membersihkan kulit dan merebusnya sampai matang'
          '\nPotong cingur dengan ukuran kecil dan sesuai selera'
          '\nRebus kangkung sampai matang'
          '\nRendam taoge di air panas hingga matang, lalu tiriskan air rebusannya'
          '\nCuci bersih dan potong timun dan bengkuang, sisihkan'
          '\nGoreng tahu dan tempe hingga matang lalu potong sesuai dengan selera'
          '\nUntuk membuat bumbu, sediakan cobek besar untuk menghaluskan cabai rawit, kacang tanah, bawang putih, garam, gula merah, dan pisang klutuk'
          '\nSetelah bumbu diuleg secara halus dan merata, tambahkan petis udang, air asam jawa, dan air secukupnya'
          '\nAmbil piring saji dan tata sayur, cingur, tahu juga tempe'
          '\nSiram bumbu rujak saus petis di atasnya'
          '\nKamu bisa menambahkan lontong untuk dicampur dengan sayuran sebelum dituang bumbu'
          '\nSediakan dengan kerupuk '
          '\nRujak cingur pun siap untuk disantap',
      gambar: 'images/7.jpg'),
  Makanan(
      nama: 'Sate Bulayak',
      khas: 'Mandalika',
      description:
          'Mandalika bukan hanya punya objek wisata yang memanjakan mata,'
          ' Mandalika juga punya kuliner pemanja lidah. Salah satunya, Mandalika'
          ' punya sate bulayak. Dinamakan bulayak karena sate daging ini disajikan'
          ' bersama lontong ketan yang dililit daun aren khas Lombok bernama'
          ' bulayak. Daging pilihan sate ini pun bermacam-macam, bisa menggunakan'
          ' daging sapi maupun ayam.'
          '\n'
          '\nBahan utamanya:'
          '\n400 gram daging sapi, potong dadu'
          '\n100 gram kelapa setengah tua, parut'
          '\n75 gram kacang tanah goreng, tumbuk'
          '\n200 ml santan kental'
          '\n1 sdm air jeruk nipis'
          '\n2 sdm gula merah, serut'
          '\n25 buah tusuk sate'
          '\n10 buah bulayak'
          '\n'
          '\nBahan bumbu halus:'
          '\n12 buah cabai rawit merah'
          '\n6 siung bawang merah'
          '\n4 siung bawang putih'
          '\n1 sdt merica'
          '\nGaram secukupnya'
          '\n'
          '\nlangkah-langkah pembuatannya'
          '\n1. Baluri daging dengan air jeruk nipis, diamkan selama 15 menit. Kemudian, campur daging dengan setengah bumbu halus dan kelapa parut, aduk rata.'
          '\n2. Tusuk sate ke dalam tusukan sate, kukus selama 20 menit atau hingga matang.'
          '\n3. Siapkan alat pembakaran, bakar sate hingga kecokelatan.'
          '\n4. Panaskan minyak goreng, lalu tumis bumbu halus hingga harum.'
          '\n Masukkan kacang tanah tumbuk, gula merah, dan santan. Aduk merata hingga mengental.'
          '\n5. Siapkan piring, lalu letakkan sate bulayak di atasnya bersama sambal kacang. Sate bulayak siap disajikan.',
      gambar: 'images/8.jpg'),
  Makanan(
      nama: 'Soto Ayam Ambengan',
      khas: 'Surabaya',
      description:
          'Soto Ambengan merupakan salah satu soto khas Surabaya. Kata “Ambengan”'
          ' berasal dari salah satu depot soto ayam bernama Soto Ayam Pak Sadi '
          ' yang letaknya berada di jalan Ambengan, Surabaya. Karena terkenal akan'
          ' kelezatannya, masyarakat sekitar menyebutnya dengan “Soto Ambengan.”'
          ' Sekilas, soto ini terlihat sama dengan soto ayam Lamongan karena kuah'
          ' keduanya yang berwarna bening kuningan.'
          '\nSelain itu, soto Ambengan juga terdiri dari soun, suwiran daging'
          ' ayam, serta kol. Akan tetapi, ciri khas yang membedakannya adalah '
          ' adanya taburan bubuk koya yang membuat rasanya bertambah gurih. Bubuk'
          ' koya terbuat dari campuran bawang merah dan bawang putih goreng serta '
          ' kerupuk udang yang telah dihancurkan.'
          '\n'
          '\nBahan-bahan:'
          '\nHasil 4 porsi'
          '\nAyam kampung, belah 4 - 1/2 ekor'
          '\nDaun salam - 2 lembar'
          '\nDaun jeruk - 6 lembar'
          '\nJahe, memarkan - 2 cm'
          '\nSerai, memarkan - 2 batang'
          '\nLengkuas - 3 cm'
          '\nGaram - 1,5 sdm'
          '\nGula pasir - 1 sdt'
          '\nMinyak untuk menumis - 3 sdm'
          '\nAir, untuk merebus - 2 liter'
          '\n'
          '\nBUMBU HALUS:'
          '\nBawang merah - 10 butir'
          '\nBawang putih - 8 siung'
          '\nKemiri, sangrai - 5 butir'
          '\nKunyit, bakar - 2 cm'
          '\nMerica - 1/2 sdt'
          '\nKetumbar - 1 sdt'
          '\n'
          '\nBUBUK KOYA:'
          '\nBawang putih, iris tipis - 5 siung'
          '\nKerupuk udang, goreng matang - 15 buah'
          '\nGaram - 1/4 sdt'
          '\n'
          '\nPELENGKAP:'
          '\nSoun - secukupnya'
          '\nTelur rebus, belah - secukupnya'
          '\nKubis, iris halus - secukupnya'
          '\nSeledri, iris - secukupnya'
          '\nDaun bawang, iris - secukupnya'
          '\nBawang merah goreng - secukupnya',
      gambar: 'images/9.jpg'),
  Makanan(
      nama: 'Sup Ikan Jantung Pisang',
      khas: 'Sulawesi Tengah',
      description:
          'Kuliner Unik Nusantara ini memiliki cita rasa yang khas perpaduan '
          'rempah, bawang merah, bawang putih, jahe, serai, kunyit, lengkuas, daun '
          'salam, dan cabe rawit.'
          'Makanan ini adalah perpaduan ikan kakap dan jantung pisang yang direbus'
          'dalam kuah rempah.'
          '\n'
          '\nBahan-bahan:'
          '\n200 gr daging ikan kakap, potong kecil, balur dengan air jeruk'
          'nipis dan garam'
          '\n1 liter air'
          '\n250 gr irisan jantung pisang'
          '\n1 buah tomat'
          '\n1 sdt garam'
          '\n2 sdm air jeruk nipis'
          '\n'
          '\nBumbu-Bumbu :'
          '\n2 batang serai, memarkan'
          '\n2 siung bawang putih, memarkan'
          '\n5 butir bawang merah, memarkan'
          '\n2 buah cabai merah besar, iris'
          '\n1 ikat rempah daun (daun pandan, kemangi, daun kunyit).'
          '\n'
          '\nCara Membuat Gulai Ikan Jantung Pisang:'
          '\n1. Rebus air, masukkan bumbu-bumbu dan ikan serta air jeruk nipis'
          'dan garam.'
          '\n2. Masak hingga mendidih. Masukkan tomat dan jantung pisang, aduk'
          'rata. Masak sebentar.'
          '\n3. Angkat, kemudian hidangkan.',
      gambar: 'images/10.jpg')
];
